(message "loading conf/fundamentals-conf")
(require 'vertico-conf)
(require 'consult-conf)
(require 'browse-kill-ring-conf)
(require 'undo-tree-conf)
(require 'projectile-conf)
(require 'uniquify-conf)
(require 'multiple-cursors-conf)
(require 'magit-conf)
(require 'winner-mode-conf)
(require 'ediff-conf)
(require 'whitespace-mode-conf)
(require 'window-setup-conf)
(require 'tabs-or-spaces-conf)
(require 'scroll-conf)

(provide 'fundamentals-conf)
