(require 'helm-conf)
(require 'browse-kill-ring-conf)
(require 'undo-tree-conf)
(require 'projectile-conf)
(require 'helm-ag-conf)
(require 'helm-projectile-conf)
(require 'uniquify-conf)
(require 'multiple-cursors-conf)
(require 'magit-conf)
(require 'winner-mode-conf)
(require 'ediff-conf)

(provide 'fundamentals-conf)
