(require 'windmove)
(require 'dash)

(defun bleadof/term ()
  (ansi-term "/bin/bash"))

(defun bleadof/send-term (command)
  (when (not (equal command nil))
    (insert command)
    (term-send-input)))

(defun bleadof/term-git-root (&optional command)
  (bleadof/term)
  (bleadof/send-term "gr")
  (bleadof/send-term command))

(defun bleadof/basic-window-setup (&optional term1 term2 term3)
  (interactive)
  (delete-other-windows)
  (split-window-below (- (window-height) (/ (window-height) 4)))
  (split-window-right)
  (windmove-down)
  (-dotimes 2
    (lambda (num)
      (split-window-right (- (window-width) (/ (window-width) 3)))))
  (bleadof/term-git-root term1)
  (windmove-right)
  (bleadof/term-git-root term2)
  (windmove-right)
  (bleadof/term-git-root term3)
  (select-window (frame-first-window))
  (message "NOW CODE!"))

(defun bleadof/basic-window-clean ()
  (interactive)
  (select-window (frame-first-window))
  (windmove-down)
  (kill-buffer)
  (-dotimes 2
    (lambda (num)
      (windmove-right)
      (kill-buffer)))
  (select-window (frame-first-window))
  (delete-other-windows))

(provide 'bleadof-basic-window-setup)
